---
title: "Modelling of Selected Stock Price"
subtitle: "Using ML Model"
output: html_document
---

# Setup
```{r setup, include = F, echo = T}
library(dplyr)
library(data.table)
library(prophet)

TRAIN_DT <- as.Date("2021-01-01")

if (as.character(Sys.info()["nodename"]) == "ND0151MB") {
  board_nm <- "Portfolio Management"
}

if (as.character(Sys.info()["nodename"]) == "copernicus64gb") {
  board_nm <- "Portfolio Management (Copernicus)"
}

if (!(as.character(Sys.info()["nodename"]) %in% c("copernicus64gb", "ND0151MB"))) {
  board_nm <- "Portfolio Management"
}
```

## Load Modelling Data for `MasterCard`, i.e. `MA`
```{r Modelling Data}
# ----- Register Board -----
pins::board_register_local(name = board_nm)

# ----- Load Data -----
modelling_data <- 
  
  # - Download Data
  pins::pin_get("modelling_data_1.05_ret_10_wind", board_nm) %>% 
  as.data.frame() %>% 
  
  # create factor TARGET
  dplyr::mutate(
    target = as.factor(dplyr::if_else(target_10w > 0, "Over", "Under"))
  ) %>% 
  as.data.frame() %>% 
  
  # - split train/test
  dplyr::mutate(
    sample_type = dplyr::if_else(dt < TRAIN_DT, "Train", "Test")
  ) %>% 
  
  # - Remove columns
  dplyr::select(-open, -high, -low, -close, -p_adjusted, -volume) %>% 
  dplyr::mutate_if(is.character, as.factor) %>% 
  
  # - Select specific ticker
  dplyr::filter(ticker %in% c("MA")) %>% 
  as.data.frame()
```

## Load Raw Data for `MA`
```{r Raw Data}
raw_data <- 
  
  # - Download Data
  pins::pin_get("md_stock_prices", board_nm) %>% 
  as.data.frame() %>% 
  
  # - Select specific ticker
  dplyr::filter(ticker %in% c("MA") & volume > 0) %>% 
  as.data.frame()
```

# Modelling using `prophet`
```{r prophet}
```